# Generated by Django 4.1.4 on 2022-12-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0008_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=50)),
                ('roles', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('states', models.CharField(max_length=10)),
                ('levels', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('GST', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('hsn', models.CharField(max_length=50)),
                ('gst', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('manufacture', models.CharField(max_length=50)),
                ('uom', models.CharField(max_length=50)),
            ],
        ),
    ]
