# Generated by Django 4.1.4 on 2022-12-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0010_vendorlist_warehouselist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouselist',
            old_name='category',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='warehouselist',
            old_name='hsn',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='warehouselist',
            old_name='item_code',
            new_name='licence',
        ),
        migrations.RenameField(
            model_name='warehouselist',
            old_name='item_name',
            new_name='pan',
        ),
        migrations.RenameField(
            model_name='warehouselist',
            old_name='manufacture',
            new_name='wh_id',
        ),
        migrations.RenameField(
            model_name='warehouselist',
            old_name='uom',
            new_name='wh_manager',
        ),
        migrations.AddField(
            model_name='warehouselist',
            name='wh_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
