# Generated by Django 4.1.4 on 2022-12-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0011_rename_category_warehouselist_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key='True', serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
