# Generated by Django 4.1.4 on 2022-12-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0012_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='free_quantity',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemlist',
            name='lpp',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemlist',
            name='mrp',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
