# Generated by Django 4.1.4 on 2022-12-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0013_itemlist_free_quantity_itemlist_lpp_itemlist_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='mrp',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
