# Generated by Django 4.1.4 on 2022-12-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0014_alter_itemlist_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='gst_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='lic_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='pan_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
