# Generated by Django 4.1.4 on 2022-12-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0015_warehouse_gst_image_warehouse_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='gst_image',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='image',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='lic_image',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='pan_image',
        ),
        migrations.AddField(
            model_name='warehouselist',
            name='gst_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouselist',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouselist',
            name='lic_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouselist',
            name='pan_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
