# Generated by Django 4.1.4 on 2022-12-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0017_region_address_region_contact_no_region_gst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(max_length=50, primary_key='True', serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
