# Generated by Django 4.1.4 on 2022-12-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0019_city_level_state_category_status_designation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GST',
            fields=[
                ('id', models.CharField(max_length=50, primary_key='True', serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(max_length=50, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='uom',
            name='id',
            field=models.CharField(max_length=50, primary_key='True', serialize=False),
        ),
    ]
