# Generated by Django 4.1.4 on 2022-12-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0020_gst_alter_category_id_alter_uom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='sno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
