# Generated by Django 4.1.4 on 2022-12-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0021_itemlist_sno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grn_item_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('UOM', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField()),
                ('image', models.ImageField(max_length=10, upload_to='')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='sno',
            field=models.IntegerField(null=True),
        ),
    ]
