# Generated by Django 4.1.4 on 2022-12-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0022_grn_item_list_alter_itemlist_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn_item_list',
            name='mrp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
