# Generated by Django 4.1.4 on 2022-12-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0023_grn_item_list_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn_item_list',
            name='expiry_date',
            field=models.DateField(default=0),
        ),
    ]
