# Generated by Django 4.1.4 on 2022-12-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0026_alter_grn_item_list_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('inv_id', models.IntegerField()),
                ('inv_date', models.DateField(auto_now=True, null=True)),
                ('inv_amount', models.IntegerField()),
                ('grn', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('mrp', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='grn_item_list',
            name='expiry_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
