# Generated by Django 4.1.4 on 2022-12-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0028_alter_grn_grn'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelist',
            name='store_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
