# Generated by Django 4.1.4 on 2022-12-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0029_storelist_store_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelist',
            name='address',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storelist',
            name='contact_person',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
