# Generated by Django 4.1.4 on 2022-12-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0030_storelist_address_storelist_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
