# Generated by Django 4.1.4 on 2022-12-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0034_remove_inventorylist_netqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylist',
            name='margin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorylist',
            name='mrp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
