# Generated by Django 4.1.4 on 2022-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0036_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(blank=True, max_length=50, null=True)),
                ('sonumber', models.CharField(blank=True, max_length=50, null=True)),
                ('itemcount', models.IntegerField()),
                ('date', models.DateField(auto_now=True, null=True)),
                ('dcnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
