# Generated by Django 4.1.4 on 2022-12-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0037_deliverychallan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
