# Generated by Django 4.1.4 on 2022-12-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0038_alter_deliverychallan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='itemcount',
            field=models.FloatField(),
        ),
    ]
