# Generated by Django 4.1.4 on 2022-12-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0039_alter_deliverychallan_itemcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='itemcount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
