# Generated by Django 4.1.4 on 2022-12-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0040_alter_deliverychallan_itemcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='itemcount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
