# Generated by Django 4.1.4 on 2022-12-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0041_alter_deliverychallan_itemcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelist',
            name='pan',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='itemcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
