# Generated by Django 4.1.4 on 2022-12-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0042_storelist_pan_alter_deliverychallan_itemcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelist',
            name='gst_attach',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='storelist',
            name='lic_attach',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='storelist',
            name='pan_attach',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='storelist',
            name='store_attach',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='storelist',
            name='trade_attach',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
