# Generated by Django 4.1.4 on 2022-12-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0043_storelist_gst_attach_storelist_lic_attach_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storelist',
            old_name='lic_attach',
            new_name='food_attach',
        ),
    ]
