# Generated by Django 4.1.4 on 2022-12-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0044_rename_lic_attach_storelist_food_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlist',
            name='gstattach',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vendorlist',
            name='pan_attach',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
