# Generated by Django 4.1.4 on 2022-12-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0046_user_designation_user_level_user_region_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, max_length=10, upload_to=''),
            preserve_default=False,
        ),
    ]
