# Generated by Django 4.1.4 on 2022-12-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0047_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
