# Generated by Django 4.1.4 on 2022-12-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0048_region_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
