# Generated by Django 4.1.4 on 2022-12-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0049_alter_region_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('batch', models.CharField(blank=True, max_length=10, null=True)),
                ('expdate', models.DateField(auto_now=True, null=True)),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manufacture', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.IntegerField()),
                ('img', models.ImageField(max_length=10, upload_to='')),
            ],
        ),
    ]
