# Generated by Django 4.1.4 on 2022-12-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0050_saleitemlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
