# Generated by Django 4.1.4 on 2022-12-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0051_grn_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indent_Item_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('indent_no', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.IntegerField()),
                ('mrp', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('expirydate', models.DateField(auto_now=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
