# Generated by Django 4.1.4 on 2022-12-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0053_indent_item_list_dispatch_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indent_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
